[server]
headless = true
enableCORS = false
enableXsrfProtection = true
maxUploadSize = 50

[browser]
gatherUsageStats = false

[theme]
base = "dark"
primaryColor = "#0878ff"
backgroundColor = "#061423"
secondaryBackgroundColor = "#0b1e31"
textColor = "#f4f8ff"
